### ISSUE TITLE
关键点导出 COCO 数据类型

### ISSUE THREAD

**Issue by jin-s13** [open-mmlab/labelbee-client#10]
LabelBee-Client 的目标检测、语义分割支持直接导出 COCO 数据类型，但是关键点检测好像还不支持。
后续有计划支持嘛？

**Comment by Kerwin-L** [comment]
这边标点工具后续会增加一种列表标注的模式，该模式才适合进行 coco 格式的导出。后续等功能完成后将会一起支持 COCO 关键点格式的导出。

**Comment by jin-s13** [comment]
赞！
