### ISSUE TITLE
导出的coco格式是否可以自动加入“area”属性

### ISSUE THREAD

**Issue by minasora** [open-mmlab/labelbee-client#11]
标注后现在导出的coco格式json里annoations下没有area属性，不能直接用在mmdet里，能否在导出时自动添加呢

**Comment by Kerwin-L** [comment]
可以的，这几天将会发布一个版本。支持 Detection 标注下，导出 coco 格式添加 area 属性

**Comment by Kerwin-L** [comment]
#13
