### ISSUE TITLE
Edge adsorption can only adsorb lines, not points

### ISSUE THREAD

**Issue by wangzy0225** [open-mmlab/labelbee-client#15]
for segmentation, Edge adsorption can only adsorb lines, not points

**Comment by Kerwin-L** [comment]
Yes, we will optimize it later. Thanks for your comment.

**Comment by wangzy0225** [comment]
您好，这个好像还有一些问题，就是现在可以实现点吸附了，但是每次只能吸附一个点，然后共边，当中间有多个点的时候还是不会自动吸附

**Comment by wangzy0225** [comment]
您好，这个好像还有一些问题，就是现在可以实现点吸附了，但是每次只能吸附一个点，然后共边，当中间有多个点的时候还是不会自动吸附

**Comment by Kerwin-L** [comment]
Please provide a more precise example? The priority of adsorption is point then edge
