### ISSUE TITLE
Using Mutiple Step Project

### ISSUE THREAD

**Issue by VincentZhao1992** [open-mmlab/labelbee-client#24]
how to click the button of next step, it's always gray.

**Comment by garvan2021** [comment]
You have to finish first step annotation to all pictures to make the `Next Step` button green. Alternetively, you can hover your mouse to `Steps` list which near to `Next Step` button to choose the step you want

**Comment by Kerwin-L** [comment]
> You have to finish first step annotation to all pictures to make the `Next Step` button green. Alternetively, you can hover your mouse to `Steps` list which near to `Next Step` button to choose the step you want

Your answer is very correct. Thank you for your answer~
