### ISSUE TITLE
工具很好用，但有两个比较基础又需要的问题

### ISSUE THREAD

**Issue by seasenzzr000** [open-mmlab/labelbee-client#26]
工具很好用，点个赞。使用了一段时间，发现有个基础功能没有完善。
1、是否可以在客户端界面展示当前图片的地址，便于查找对应图片文件？
2、是否可以提供web版本使用？

**Comment by Kerwin-L** [comment]
感谢反馈~
1. 是可以的，这边后续进行补充
2. 现暂无打算，不过后续客户端会提供远程访问服务，直接标注远程服务器的数据图片
