### ISSUE TITLE
image automatically rotation

### ISSUE THREAD

**Issue by cartvector** [open-mmlab/labelbee-client#37]
I found that labelbee will automatically rotate some pictures when opening, but the picture has no other information except the width and height, what is the rotation based on?
For example, this two images are displayed as the second, and the saved label coordinates are also the same, which will be wrong.
![image](https://user-images.githubusercontent.com/45708253/171356726-1e470944-924c-4abb-93a6-48b97f684eef.png)

**Comment by Kerwin-L** [comment]
Please upload your image? LabelBee will use EXIF to show your picture
