### ISSUE TITLE
Will the points annotation support the connection function?

### ISSUE THREAD

**Issue by gs-ren** [open-mmlab/labelbee-client#40]
For points annotation, if the connection line between points can be showed, That will be more efficient.Is there such a plan?

**Comment by Kerwin-L** [comment]
What kind of training scenarios are you supporting with this kind of annotation?

**Comment by gs-ren** [comment]
such as pose estimation，face landmarks, which need lines to distinguish each part.

**Comment by Kerwin-L** [comment]
We have considered this operation before, but the operation is not universal enough, and we will develop a feature which can only mark the corresponding list once. This approach will be able to handle such key point ( line | polygon ) tasks
