### ISSUE TITLE
为什么labelme格式的关键点标注转换为labelbee格式的两步关键点的标注在labelbee的软件界面里面无法显示？

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/labelbee-client#45]
hello  all@Kerwin-L @waqarsqureshi 
{"width": 1920, "height": 1080, "valid": true, "rotate": 0, "step1": {"dataSourceStep": 0, "toolName": "rectTool", "result": [{"x": 569, "y": 200, "width": 75, "height": 199, "attribute": "per 1", "valid": true, "id": "000000001", "sourceID": "", "textAttribute": "1", "order": 1}, {"x": 0, "y": 657, "width": 271, "height": 423, "attribute": "per 2", "valid": true, "id": "000000002", "sourceID": "", "textAttribute": "2", "order": 2}, {"x": 260, "y": 323, "width": 181, "height": 510, "attribute": "per 3", "valid": true, "id": "000000003", "sourceID": "", "textAttribute": "3", "order": 3}]}, "step2": {"dataSourceStep": 1, "toolName": "pointTool", "result": [{"x": 593, "y": 231, "attribute": "nose", "valid": true, "id": "000000001", "sourceID": "000000001", "textAttribute": "1", "order": 1}, {"x": 593, "y": 224, "attribute": "left_eye", "valid": true, "id": "000000002", "sourceID": "000000001", "textAttribute": "1", "order": 2}, {"x": 590, "y": 224, "attribute": "right_eye", "valid": true, "id": "000000003", "sourceID": "000000001", "textAttribute": "1", "order": 3}, {"x": 600, "y": 218, "attribute": "left_ear", "valid": true, "id": "000000004", "sourceID": "000000001", "textAttribute": "1", "order": 4}, {"x": 587, "y": 224, "attribute": "right_ear", "valid": true, "id": "000000005", "sourceID": "000000001", "textAttribute": "1", "order": 5}, {"x": 621, "y": 234, "attribute": "left_shoulder", "valid": true, "id": "000000006", "sourceID": "000000001", "textAttribute": "1", "order": 6}, {"x": 578, "y": 243, "attribute": "right_shoulder", "valid": true, "id": "000000007", "sourceID": "000000001", "textAttribute": "1", "order": 7}, {"x": 628, "y": 268, "attribute": "left_elbow", "valid": true, "id": "000000008", "sourceID": "000000001", "textAttribute": "1", "order": 8}, {"x": 581, "y": 280, "attribute": "right_elbow", "valid": true, "id": "000000009", "sourceID": "000000001", "textAttribute": "1", "order": 9}, {"x": 600, "y": 271, "attribute": "left_wrist", "valid": true, "id": "000000010", "sourceID": "000000001", "textAttribute": "1", "order": 10}, {"x": 596, "y": 265, "attribute": "right_wrist", "valid": true, "id": "000000011", "sourceID": "000000001", "textAttribute": "1", "order": 11}, {"x": 621, "y": 311, "attribute": "left_hip", "valid": true, "id": "000000012", "sourceID": "000000001", "textAttribute": "1", "order": 12}, {"x": 593, "y": 315, "attribute": "right_hip", "valid": true, "id": "000000013", "sourceID": "000000001", "textAttribute": "1", "order": 13}, {"x": 631, "y": 361, "attribute": "left_knee", "valid": true, "id": "000000014", "sourceID": "000000001", "textAttribute": "1", "order": 14}, {"x": 603, "y": 364, "attribute": "right_knee", "valid": true, "id": "000000015", "sourceID": "000000001", "textAttribute": "1", "order": 15}, {"x": 9, "y": 756, "attribute": "left_ear", "valid": true, "id": "000000016", "sourceID": "000000002", "textAttribute": "2", "order": 4}, {"x": 82, "y": 789, "attribute": "left_shoulder", "valid": true, "id": "000000017", "sourceID": "000000002", "textAttribute": "2", "order": 6}, {"x": 142, "y": 914, "attribute": "left_elbow", "valid": true, "id": "000000018", "sourceID": "000000002", "textAttribute": "2", "order": 8}, {"x": 175, "y": 1027, "attribute": "left_wrist", "valid": true, "id": "000000019", "sourceID": "000000002", "textAttribute": "2", "order": 10}, {"x": 311, "y": 402, "attribute": "nose", "valid": true, "id": "000000020", "sourceID": "000000003", "textAttribute": "3", "order": 1}, {"x": 319, "y": 394, "attribute": "left_eye", "valid": true, "id": "000000021", "sourceID": "000000003", "textAttribute": "3", "order": 2}, {"x": 303, "y": 394, "attribute": "right_eye", "valid": true, "id": "000000022", "sourceID": "000000003", "textAttribute": "3", "order": 3}, {"x": 343, "y": 378, "attribute": "left_ear", "valid": true, "id": "000000023", "sourceID": "000000003", "textAttribute": "3", "order": 4}, {"x": 303, "y": 386, "attribute": "right_ear", "valid": true, "id": "000000024", "sourceID": "000000003", "textAttribute": "3", "order": 5}, {"x": 375, "y": 410, "attribute": "left_shoulder", "valid": true, "id": "000000025", "sourceID": "000000003", "textAttribute": "3", "order": 6}, {"x": 287, "y": 418, "attribute": "right_shoulder", "valid": true, "id": "000000026", "sourceID": "000000003", "textAttribute": "3", "order": 7}, {"x": 407, "y": 482, "attribute": "left_elbow", "valid": true, "id": "000000027", "sourceID": "000000003", "textAttribute": "3", "order": 8}, {"x": 279, "y": 474, "attribute": "right_elbow", "valid": true, "id": "000000028", "sourceID": "000000003", "textAttribute": "3", "order": 9}, {"x": 351, "y": 474, "attribute": "left_wrist", "valid": true, "id": "000000029", "sourceID": "000000003", "textAttribute": "3", "order": 10}, {"x": 279, "y": 498, "attribute": "right_wrist", "valid": true, "id": "000000030", "sourceID": "000000003", "textAttribute": "3", "order": 11}, {"x": 375, "y": 570, "attribute": "left_hip", "valid": true, "id": "000000031", "sourceID": "000000003", "textAttribute": "3", "order": 12}, {"x": 327, "y": 578, "attribute": "right_hip", "valid": true, "id": "000000032", "sourceID": "000000003", "textAttribute": "3", "order": 13}, {"x": 391, "y": 673, "attribute": "left_knee", "valid": true, "id": "000000033", "sourceID": "000000003", "textAttribute": "3", "order": 14}, {"x": 367, "y": 657, "attribute": "right_knee", "valid": true, "id": "000000034", "sourceID": "000000003", "textAttribute": "3", "order": 15}, {"x": 407, "y": 769, "attribute": "left_ankle", "valid": true, "id": "000000035", "sourceID": "000000003", "textAttribute": "3", "order": 16}, {"x": 415, "y": 705, "attribute": "right_ankle", "valid": true, "id": "000000036", "sourceID": "000000003", "textAttribute": "3", "order": 17}]}}

**Comment by APeiZou** [comment]
hello all@Kerwin-L @waqarsqureshi
Why can't the two-step annotation parse out any visual results in the labelbee's software interface?
![企业微信截图_16593483897529](https://user-images.githubusercontent.com/49524647/182125408-3d049597-b147-4268-9e12-995324dd6872.png)


json file like following:
{"width": 1920, "height": 1080, "valid": true, "rotate": 0, "step1": {"dataSourceStep": 0, "toolName": "rectTool", "result": [{"x": 569, "y": 200, "width": 75, "height": 199, "attribute": "per 1", "valid": true, "id": "000000001", "sourceID": "", "textAttribute": "1", "order": 1}, {"x": 0, "y": 657, "width": 271, "height": 423, "attribute": "per 2", "valid": true, "id": "000000002", "sourceID": "", "textAttribute": "2", "order": 2}, {"x": 260, "y": 323, "width": 181, "height": 510, "attribute": "per 3", "valid": true, "id": "000000003", "sourceID": "", "textAttribute": "3", "order": 3}]}, "step2": {"dataSourceStep": 1, "toolName": "pointTool", "result": [{"x": 593, "y": 231, "attribute": "nose", "valid": true, "id": "000000001", "sourceID": "000000001", "textAttribute": "1", "order": 1}, {"x": 593, "y": 224, "attribute": "left_eye", "valid": true, "id": "000000002", "sourceID": "000000001", "textAttribute": "1", "order": 2}, {"x": 590, "y": 224, "attribute": "right_eye", "valid": true, "id": "000000003", "sourceID": "000000001", "textAttribute": "1", "order": 3}, {"x": 600, "y": 218, "attribute": "left_ear", "valid": true, "id": "000000004", "sourceID": "000000001", "textAttribute": "1", "order": 4}, {"x": 587, "y": 224, "attribute": "right_ear", "valid": true, "id": "000000005", "sourceID": "000000001", "textAttribute": "1", "order": 5}, {"x": 621, "y": 234, "attribute": "left_shoulder", "valid": true, "id": "000000006", "sourceID": "000000001", "textAttribute": "1", "order": 6}, {"x": 578, "y": 243, "attribute": "right_shoulder", "valid": true, "id": "000000007", "sourceID": "000000001", "textAttribute": "1", "order": 7}, {"x": 628, "y": 268, "attribute": "left_elbow", "valid": true, "id": "000000008", "sourceID": "000000001", "textAttribute": "1", "order": 8}, {"x": 581, "y": 280, "attribute": "right_elbow", "valid": true, "id": "000000009", "sourceID": "000000001", "textAttribute": "1", "order": 9}, {"x": 600, "y": 271, "attribute": "left_wrist", "valid": true, "id": "000000010", "sourceID": "000000001", "textAttribute": "1", "order": 10}, {"x": 596, "y": 265, "attribute": "right_wrist", "valid": true, "id": "000000011", "sourceID": "000000001", "textAttribute": "1", "order": 11}, {"x": 621, "y": 311, "attribute": "left_hip", "valid": true, "id": "000000012", "sourceID": "000000001", "textAttribute": "1", "order": 12}, {"x": 593, "y": 315, "attribute": "right_hip", "valid": true, "id": "000000013", "sourceID": "000000001", "textAttribute": "1", "order": 13}, {"x": 631, "y": 361, "attribute": "left_knee", "valid": true, "id": "000000014", "sourceID": "000000001", "textAttribute": "1", "order": 14}, {"x": 603, "y": 364, "attribute": "right_knee", "valid": true, "id": "000000015", "sourceID": "000000001", "textAttribute": "1", "order": 15}, {"x": 9, "y": 756, "attribute": "left_ear", "valid": true, "id": "000000016", "sourceID": "000000002", "textAttribute": "2", "order": 4}, {"x": 82, "y": 789, "attribute": "left_shoulder", "valid": true, "id": "000000017", "sourceID": "000000002", "textAttribute": "2", "order": 6}, {"x": 142, "y": 914, "attribute": "left_elbow", "valid": true, "id": "000000018", "sourceID": "000000002", "textAttribute": "2", "order": 8}, {"x": 175, "y": 1027, "attribute": "left_wrist", "valid": true, "id": "000000019", "sourceID": "000000002", "textAttribute": "2", "order": 10}, {"x": 311, "y": 402, "attribute": "nose", "valid": true, "id": "000000020", "sourceID": "000000003", "textAttribute": "3", "order": 1}, {"x": 319, "y": 394, "attribute": "left_eye", "valid": true, "id": "000000021", "sourceID": "000000003", "textAttribute": "3", "order": 2}, {"x": 303, "y": 394, "attribute": "right_eye", "valid": true, "id": "000000022", "sourceID": "000000003", "textAttribute": "3", "order": 3}, {"x": 343, "y": 378, "attribute": "left_ear", "valid": true, "id": "000000023", "sourceID": "000000003", "textAttribute": "3", "order": 4}, {"x": 303, "y": 386, "attribute": "right_ear", "valid": true, "id": "000000024", "sourceID": "000000003", "textAttribute": "3", "order": 5}, {"x": 375, "y": 410, "attribute": "left_shoulder", "valid": true, "id": "000000025", "sourceID": "000000003", "textAttribute": "3", "order": 6}, {"x": 287, "y": 418, "attribute": "right_shoulder", "valid": true, "id": "000000026", "sourceID": "000000003", "textAttribute": "3", "order": 7}, {"x": 407, "y": 482, "attribute": "left_elbow", "valid": true, "id": "000000027", "sourceID": "000000003", "textAttribute": "3", "order": 8}, {"x": 279, "y": 474, "attribute": "right_elbow", "valid": true, "id": "000000028", "sourceID": "000000003", "textAttribute": "3", "order": 9}, {"x": 351, "y": 474, "attribute": "left_wrist", "valid": true, "id": "000000029", "sourceID": "000000003", "textAttribute": "3", "order": 10}, {"x": 279, "y": 498, "attribute": "right_wrist", "valid": true, "id": "000000030", "sourceID": "000000003", "textAttribute": "3", "order": 11}, {"x": 375, "y": 570, "attribute": "left_hip", "valid": true, "id": "000000031", "sourceID": "000000003", "textAttribute": "3", "order": 12}, {"x": 327, "y": 578, "attribute": "right_hip", "valid": true, "id": "000000032", "sourceID": "000000003", "textAttribute": "3", "order": 13}, {"x": 391, "y": 673, "attribute": "left_knee", "valid": true, "id": "000000033", "sourceID": "000000003", "textAttribute": "3", "order": 14}, {"x": 367, "y": 657, "attribute": "right_knee", "valid": true, "id": "000000034", "sourceID": "000000003", "textAttribute": "3", "order": 15}, {"x": 407, "y": 769, "attribute": "left_ankle", "valid": true, "id": "000000035", "sourceID": "000000003", "textAttribute": "3", "order": 16}, {"x": 415, "y": 705, "attribute": "right_ankle", "valid": true, "id": "000000036", "sourceID": "000000003", "textAttribute": "3", "order": 17}]}}

**Comment by waqarsqureshi** [comment]
Hi,
I still cannot understand your question much.

**Comment by Kerwin-L** [comment]
Please provide more information like the config of Project.
<img width="938" alt="image" src="https://user-images.githubusercontent.com/21312795/183277182-a2707a93-1318-4823-b04b-ce008b9880ec.png">
