### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by ckxkexing** [open-mmlab/labelbee-client#46]
Hello author,
I try to clone the code and run,
But with `npm install` there are dependencies error.
I'm using 9abd54761152b1586feb5100eb71c5a6113dfccd from the main branch.
this problem can't be solved with `npm install --legacy-peer-deps`
Does this require a specific node, npm version?

**Comment by Kerwin-L** [comment]
What version of Node do you have installed?  Can you give more information?

**Comment by ckxkexing** [comment]
node version is v16.16.0
npm version is v6.14.17

**Comment by Kerwin-L** [comment]
Sorry, The current project's dependencies need to be sorted, e.g. `node-sass` can be changed to `sass`, etc.
 
You can `git pull`  to get latest code and reinstall by lowering your node version to 14.20.0, npm: 6.14.17
