### ISSUE TITLE
一边标注,一边创建新标签, Create a new label while labeling

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/labelbee-client#48]
一边标注,一边创建新标签

不要返回项目 设置 再增加新的 标签
 

Create a new label while labeling

Do not return to the project settings and add a new label

![微信截图_20220819165650](https://user-images.githubusercontent.com/6490927/185583790-ae1f4a9f-c080-4081-b451-bb952bd462b5.png)

**Comment by Kerwin-L** [comment]
You can create a new project yourself,  instead of adding tags to the original

**Comment by monkeycc** [comment]
Unknown label.  You  need to add a label to the original project

Because the new project is not sure what labels there are

Instead of letting me recreate a new project

What is required is that during the labeling process:

You can easily add labels


Instead of specifying fixed labels in the project

Because the label is not fixed
