### ISSUE TITLE
有没有交流群，有一些业务上的问题想交流讨论一下。

### ISSUE THREAD

**Issue by YIminta** [open-mmlab/labelbee-client#50]

**Comment by YIminta** [comment]
![image](https://user-images.githubusercontent.com/50685567/186311929-4239506c-f2bb-4fa1-824d-d6f115f8baeb.png)
希望可以增加一个搜索属性的功能

**Comment by Kerwin-L** [comment]
其实如果是大批量的类别需要进行标注时，整个标注的逻辑就不该是现有这样形式😂，而是融合于标注之中，这样才能最大程度的提高效率，这类的场景我们后续会考虑下~感谢反馈
